version: '3'
services:
  loan:
    platform: linux/x86_64
    build: .
    image: ags131/loan
    volumes:
      - ./data/loan:/data
      - ./data/storage:${OBJECT_STORAGE}
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl", "${FLASK_SERVER_NAME}:5000" ]
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "screeps" ]
    ports:
      - 127.0.0.1:5432:5432
  cronjob:
    build: cronJob
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./logs:/usr/app/logs"