version: '3.9'

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

networks:
  traefik-net:
    external: true

services:
  loan:
    build: .
    volumes:
      - ./data/loan:/data
      - ./data/storage:${OBJECT_STORAGE}
    networks:
      - traefik-net
    depends_on:
      postgresLoAN:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      
      - "traefik.http.routers.loan-https.rule=Host(`loan.pandascreeps.com`)"
      - "traefik.http.routers.loan-https.entrypoints=websecure"
      - "traefik.http.routers.loan-https.tls.certresolver=letsencrypt"

      - "traefik.http.routers.loan-http.rule=Host(`loan.pandascreeps.com`)"
      - "traefik.http.routers.loan-http.entrypoints=web"

      - "traefik.http.routers.loanExternal-https.rule=Host(`www.leagueofautomatednations.com`)"
      - "traefik.http.routers.loanExternal-https.entrypoints=websecure"
      - "traefik.http.routers.loanExternal-https.tls.certresolver=letsencrypt"

      - "traefik.http.routers.loanExternal-http.rule=Host(`www.leagueofautomatednations.com`)"
      - "traefik.http.routers.loanExternal-http.entrypoints=web"
    logging: *default-logging
    ports:
      - 5002:5000
  postgresLoAN:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - traefik-net
    logging: *default-logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "screeps"]
    ports:
      - 5434:5432
  pgbackups:
    image: kartoza/pg-backup:14-3.2
    restart: always
    logging: *default-logging
    depends_on:
      - postgresLoAN
    networks:
      - traefik-net
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASS=${DB_PASSWORD}
        - POSTGRES_DB=${DB}
        - POSTGRES_HOST=postgresLoAN
    volumes:
        - /var/opt/pgbackups:/backups
  cronjob:
    build: cronJob
    logging: *default-logging
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./logs:/usr/app/logs"
    networks:
      - traefik-net
