version: '3'
services:
  loan:
    platform: linux/x86_64
    build: .
    image: ags131/loan
    volumes:
      - ./data/loan:/data
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
