version: '3'
services:
  loan:
    platform: linux/x86_64
    build: .
    image: ags131/loan
    environment:
      SETTINGS: /app/settings
    volumes:
      - ./data/loan:/data
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: screeps
      POSTGRES_DB: screeps
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
